import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Check, ChevronRight, Cpu, Database, Eye, EyeOff, FolderOpen, HardDrive, KeyRound, Save, ShieldCheck, SlidersHorizontal, Wrench } from 'lucide-react'

const providerInfo = [
  { id: 'groq', name: 'Groq', detail: 'Transcription, script intelligence, scene planning, AI direction', placeholder: 'gsk_…' },
  { id: 'elevenlabs', name: 'ElevenLabs', detail: 'Voice discovery, previews, narration, emotional delivery', placeholder: 'sk_…' },
  { id: 'pixabay', name: 'Pixabay', detail: 'Licensed stock video and image discovery', placeholder: 'API key' },
  { id: 'pexels', name: 'Pexels', detail: 'Licensed stock footage, photography, and visual search', placeholder: 'API key' }
] as const

export function Settings(): React.JSX.Element {
  const queryClient = useQueryClient(); const [active, setActive] = useState('providers'); const [values, setValues] = useState<Record<string,string>>({}); const [visible, setVisible] = useState<Record<string,boolean>>({}); const [saved, setSaved] = useState('')
  const { data: system } = useQuery({ queryKey: ['system'], queryFn: () => window.videoReplica.system.snapshot() })
  const { data: status } = useQuery({ queryKey: ['provider-status'], queryFn: () => window.videoReplica.settings.providerStatus() })
  const save = useMutation({ mutationFn: ({ provider, value }: { provider: string; value: string }) => window.videoReplica.settings.saveApiKey(provider, value), onSuccess: (_, item) => { setSaved(item.provider); setValues((all) => ({ ...all, [item.provider]: '' })); void queryClient.invalidateQueries({ queryKey: ['provider-status'] }); void queryClient.invalidateQueries({ queryKey: ['system'] }); window.setTimeout(() => setSaved(''), 1800) } })
  const sections = [{ id: 'providers', label: 'AI & providers', icon: KeyRound }, { id: 'system', label: 'System & tools', icon: Wrench }, { id: 'storage', label: 'Storage', icon: Database }, { id: 'preferences', label: 'Preferences', icon: SlidersHorizontal }]
  return <div className="settings-page"><div className="page-heading"><div><span className="eyebrow">STUDIO CONFIGURATION</span><h1>Settings</h1><p>Private by design. Credentials stay encrypted on this device.</p></div></div><div className="settings-layout"><aside>{sections.map(({ id, label, icon: Icon }) => <button key={id} className={active === id ? 'active' : ''} onClick={() => setActive(id)}><Icon /> {label}<ChevronRight /></button>)}</aside><main>
    {active === 'providers' && <><div className="settings-section-head"><div><h2>AI & media providers</h2><p>Connect the four services that power the complete production pipeline.</p></div><div className="security-chip"><ShieldCheck /> OS-encrypted storage</div></div><div className="provider-list">{providerInfo.map((provider) => <section key={provider.id}><div className="provider-logo">{provider.name.slice(0,2).toUpperCase()}</div><div className="provider-meta"><div><strong>{provider.name}</strong><span className={status?.[provider.id] ? 'connected' : ''}><i /> {status?.[provider.id] ? 'Connected' : 'Not configured'}</span></div><p>{provider.detail}</p><div className="key-input"><KeyRound /><input type={visible[provider.id] ? 'text' : 'password'} placeholder={status?.[provider.id] ? '••••••••••••••••••••••••' : provider.placeholder} value={values[provider.id] ?? ''} onChange={(event) => setValues({ ...values, [provider.id]: event.target.value })} /><button onClick={() => setVisible({ ...visible, [provider.id]: !visible[provider.id] })}>{visible[provider.id] ? <EyeOff /> : <Eye />}</button><button className="save-key" disabled={!values[provider.id]?.trim() || save.isPending} onClick={() => save.mutate({ provider: provider.id, value: values[provider.id]! })}>{saved === provider.id ? <><Check /> Saved</> : <><Save /> Save key</>}</button></div></div></section>)}</div></>}
    {active === 'system' && <><div className="settings-section-head"><div><h2>Production system</h2><p>Detected runtimes and media tools used by the local engine.</p></div></div><div className="machine-card"><Cpu /><div><span>Processor</span><strong>{system?.cpuModel ?? 'Detecting…'}</strong><small>{system?.cpuCores ?? '—'} logical threads · {system?.totalMemoryGb ?? '—'} GB memory</small></div></div><div className="tool-list">{system?.tools.map((tool) => <div key={tool.name}><div className={tool.available ? 'tool-ok' : 'tool-missing'}>{tool.available ? <Check /> : '!'}</div><section><strong>{tool.name}</strong><p>{tool.version ?? 'Not detected; packaged fallback will be used when available.'}</p></section><span>{tool.available ? 'READY' : 'OPTIONAL'}</span></div>)}</div></>}
    {active === 'storage' && <><div className="settings-section-head"><div><h2>Storage & cache</h2><p>Projects, previews, downloads, and renders stay on your device.</p></div></div><div className="storage-card"><HardDrive /><div><span>Video Replica workspace</span><strong>{system?.userDataPath ?? 'Loading…'}</strong><p>Automatic caching avoids duplicate downloads. Project files are isolated by production.</p></div><button onClick={() => window.videoReplica.system.openFolder('Projects')}><FolderOpen /> Open</button></div><div className="storage-actions"><button onClick={() => window.videoReplica.system.openFolder('Cache')}>Open cache</button><button onClick={() => window.videoReplica.system.openFolder('Exports')}>Open exports</button><button onClick={() => window.videoReplica.system.openFolder('Logs')}>Open logs</button></div></>}
    {active === 'preferences' && <><div className="settings-section-head"><div><h2>Creative defaults</h2><p>Starting points used whenever you create a new production.</p></div></div><div className="preference-list"><label><div><strong>Hardware acceleration</strong><p>Use the best available GPU encoder for previews and exports.</p></div><input type="checkbox" defaultChecked /></label><label><div><strong>Automatic project recovery</strong><p>Persist every timeline decision and reopen after a crash.</p></div><input type="checkbox" defaultChecked /></label><label><div><strong>Licensed media only</strong><p>Restrict discovery to connected stock providers.</p></div><input type="checkbox" defaultChecked /></label></div></>}
  </main></div></div>
}
